### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by cmd0s** [Web3-Pi/basic-eth2-node-monitor#1]
Aplikacja powinna się poprawnie uruchomić i działać niezależnie od tego kiedy zostanie uruchomiona.
W idealnym przypadku aplikacja jest uruchamiana kiedy klient execution, consensus i basic node monitor są uruchomione i działają poprawnie.
W realnym świecie dowolna z tych aplikacji może nie być uruchomiona, albo zostać uruchomiona później, czy też zrestartowana.
Aplikacja powinna się sama zrekonektować jak nie jest z jakimś komponentem połaczona.

**Comment by shadeofblue** [comment]
closing for now, since the issue seems to have been addressed
